import { _electron as electron } from "playwright";
import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import assert from "node:assert/strict";
import type { Request, ResponseMap } from "../src/shared/contracts";

const run = resolve("outputs/onboarding-qa", Date.now().toString());
await mkdir(join(run, "profile"), { recursive: true });
const source = join(run, "source");
await mkdir(source);
await writeFile(join(source, "notes.txt"), "Onboarding integration fixture.\n");
const env: Record<string, string> = { ...Object.fromEntries(Object.entries(process.env).filter((pair): pair is [string, string] => typeof pair[1] === "string")), SENTRY_QA: "1", SENTRY_DATA_DIR: join(run, "profile") };
delete env.ELECTRON_RUN_AS_NODE;
const app = await electron.launch({ executablePath: resolve("node_modules/electron/dist/electron.exe"), args: [resolve(".")], env, timeout: 30000 });
const page = await app.firstWindow();
const errors: string[] = [];
const evidence: Record<string, unknown> = { run };
page.on("pageerror", (error) => errors.push(error.message));
async function request<T extends Request>(value: T): Promise<ResponseMap[T["type"]]> {
  return page.evaluate((r) => window.sentry.request(r), value) as Promise<ResponseMap[T["type"]]>;
}
async function shot(name: string) {
  await page.evaluate(() => { for (const animation of document.getAnimations()) if (animation.effect?.getComputedTiming().iterations !== Infinity) animation.finish(); });
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.invalidate());
  await page.waitForTimeout(150);
  const png = await app.evaluate(async ({ BrowserWindow }) => (await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString("base64"));
  await writeFile(join(run, `${name}.png`), Buffer.from(png, "base64"));
  const layout = await page.evaluate(() => ({ width: innerWidth, height: innerHeight, scrollWidth: document.documentElement.scrollWidth }));
  assert.ok(layout.scrollWidth <= layout.width, `Horizontal overflow in ${name}`);
  evidence[name] = layout;
}
async function size(width: number, height: number, zoom = 1) {
  const state = await request({ type: "state" });
  await request({ type: "settings", settings: { ...state.settings, uiScale: zoom * 100 } });
  await app.evaluate(({ BrowserWindow }, value) => { const win = BrowserWindow.getAllWindows()[0]; win.setSize(value.width, value.height); win.webContents.setZoomFactor(value.zoom); }, { width, height, zoom });
  await page.waitForFunction((value) => Math.abs(innerWidth - value.width / value.zoom) <= 1, { width, zoom });
}
try {
  await page.locator(".setup").waitFor();
  evidence.security = await app.evaluate(({ BrowserWindow }) => { const w = BrowserWindow.getAllWindows()[0]; return { visible: w.isVisible(), offscreen: w.webContents.isOffscreen() }; });
  assert.equal((evidence.security as { visible: boolean }).visible, false);
  await shot("01-welcome-dark-1180");
  await size(2560, 1390);
  await shot("01b-welcome-dark-2560");
  await size(820, 600);
  await shot("01c-welcome-dark-820");
  await size(1180, 780);
  await page.getByRole("button", { name: "Pause setup animations", exact: true }).click();
  assert.equal(await page.locator(".setup").getAttribute("data-paused"), "true");
  await page.getByRole("button", { name: "Set up later", exact: true }).click();
  await page.locator(".sidebar").waitFor();
  assert.equal((await request({ type: "state" })).settings.onboardingDismissed, true);
  await page.reload();
  await page.locator(".sidebar").waitFor();
  await page.getByRole("button", { name: "Guided setup", exact: true }).click();
  await page.getByRole("button", { name: "Already have a backup? Connect it here", exact: true }).click();
  await page.getByRole("tab", { name: "Destinations", exact: true }).waitFor();
  assert.equal(await page.getByRole("tab", { name: "Destinations", exact: true }).getAttribute("aria-selected"), "true");
  await page.getByRole("button", { name: "Overview", exact: true }).click();
  await page.getByRole("button", { name: "Guided setup", exact: true }).click();
  await page.getByRole("button", { name: "Get started", exact: true }).focus();
  await page.keyboard.press("Enter");
  await page.getByRole("heading", { name: "Start with what matters." }).waitFor();
  assert.equal(await page.locator("#setup-heading").evaluate((el) => el === document.activeElement), true);
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByText("Choose at least one file or folder to back up.", { exact: true }).waitFor();
  await shot("02-source-validation");
  await page.getByLabel("Plan name", { exact: true }).fill("Onboarding recovery fixture");
  await page.getByLabel("Files and folders", { exact: true }).fill(join(run, "missing-source"));
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("button", { name: "Add a destination", exact: true }).click();
  await shot("03-destination-form");
  await page.getByLabel("Destination name", { exact: true }).fill("Onboarding local repository");
  await page.getByLabel("Repository folder", { exact: true }).fill(join(run, "repository"));
  await page.getByLabel("Repository password", { exact: true }).fill("onboarding-fixture-password");
  await page.getByRole("button", { name: "Create destination", exact: true }).click();
  await page.getByRole("radio").waitFor({ timeout: 30000 });
  assert.equal(await page.getByRole("radio").isChecked(), true);
  assert.equal(await page.getByLabel("Repository password", { exact: true }).count(), 0);
  await shot("04-destination-selected");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("combobox", { name: "Backup schedule" }).focus();
  await page.keyboard.press("Space");
  await page.getByRole("listbox").waitFor();
  await page.getByRole("option", { name: "Only when I start a backup", exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[aria-label="Backup schedule"]')?.textContent?.includes("Only when"));
  await shot("05-schedule-manual");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("button", { name: "Save backup plan", exact: true }).click();
  await page.locator(".setup-error").waitFor({ timeout: 30000 });
  assert.equal((await request({ type: "state" })).plans.length, 0);
  await shot("06-engine-rejection");
  await page.getByRole("button", { name: "Edit files", exact: true }).click();
  assert.equal(await page.getByLabel("Plan name", { exact: true }).inputValue(), "Onboarding recovery fixture");
  await page.getByLabel("Files and folders", { exact: true }).fill(source);
  await page.getByRole("button", { name: "Set up later", exact: true }).click();
  await page.getByRole("dialog").waitFor();
  await page.getByRole("button", { name: "Keep setting up", exact: true }).click();
  for (let step = 0; step < 3; step++) await page.getByRole("button", { name: "Continue", exact: true }).click();
  await shot("07-review-dark");
  const state = await request({ type: "state" });
  await request({ type: "settings", settings: { ...state.settings, theme: "light" } });
  // Hidden renderers refresh on a visibility event without ever showing their window.
  await page.evaluate(() => document.dispatchEvent(new Event("visibilitychange")));
  await page.waitForFunction(() => document.documentElement.dataset.theme === "light");
  await size(820, 600);
  await shot("08-review-light-820");
  await size(1180, 780, 2);
  await page.emulateMedia({ reducedMotion: "reduce" });
  evidence.reducedMotionAnimations = await page.evaluate(() => document.getAnimations().filter((animation) => animation.playState === "running").length);
  assert.equal(evidence.reducedMotionAnimations, 0);
  await shot("09-review-light-200-percent");
  await page.getByRole("button", { name: "Save backup plan", exact: true }).scrollIntoViewIfNeeded();
  await shot("09b-review-actions-light-200-percent");
  await page.getByRole("button", { name: "Save backup plan", exact: true }).click();
  await page.getByRole("heading", { name: "Your plan is ready.", exact: true }).waitFor();
  await shot("10-saved-light-200-percent");
  const saved = await request({ type: "state" });
  assert.equal(saved.plans.length, 1);
  assert.equal(saved.jobs.length, 0);
  assert.equal(saved.plans[0].schedule.kind, "manual");
  await size(1180, 780);
  await page.getByRole("button", { name: "Start first backup", exact: true }).click();
  await page.locator(".sidebar").waitFor();
  let backup;
  const deadline = Date.now() + 45000;
  do {
    backup = (await request({ type: "state" })).jobs.find((job) => job.kind === "backup" && job.planId === saved.plans[0].id);
    if (backup && !["queued", "running"].includes(backup.status)) break;
    await page.waitForTimeout(250);
  } while (Date.now() < deadline);
  evidence.backup = { status: backup?.status, snapshotId: backup?.snapshotId };
  assert.equal(backup?.status, "success", backup?.error);
  await page.reload();
  await page.locator(".sidebar").waitFor();
  assert.equal(await page.locator(".setup").count(), 0);
  evidence.keyboard = "Primary entry and heading focus; schedule selected through Radix option";
  evidence.errors = errors;
  assert.deepEqual(errors, []);
  console.log(JSON.stringify(evidence, null, 2));
} catch (error) {
  evidence.failure = String(error);
  await page.screenshot({ path: join(run, "failure.png") }).catch(() => {});
  throw error;
} finally {
  await writeFile(join(run, "results.json"), JSON.stringify({ ...evidence, errors }, null, 2));
  await app.close();
}
